### ISSUE TITLE
Tracking issue: WordPress Directives Plugin 🎨

### ISSUE THREAD

**Issue by luisherranz** [luisherranz/block-hydration-experiments#80]
This issue aims to list and keep track of the tasks related to the WordPress Directives Plugin experiment. The goal is to create an installable plugin that adds a set of basic directives and client-side navigations to any site.

_For this experiment's stress-testing, please check the [Tracking Issue: Performance and stress-testing vDOM Hydration 🧪](https://github.com/WordPress/block-hydration-experiments/issues/92)_

_For the Custom Elements or Directives Hydration experiment, please check their corresponding [Tracking Issues](https://github.com/WordPress/block-hydration-experiments/issues)._

The main branch of this experiment is [`main-wp-directives-plugin`](https://github.com/WordPress/block-hydration-experiments/tree/main-wp-directives-plugin). Make sure you select it when opening a pull request if it is related to this experiment.

Please proactively comment on this issue whenever you start working on a new task, get blocked, or finish a task, sharing as much detail and information as possible. Thanks!!

# High-level overview

- **Directives**

  - Finish the directives of the initial list - **In progress** 🚧

    Work on the directives is still reactive as we only work on the ones that we need for our experiments, demos, etc. The work on the Movies demo and Woo blocks should bring some focus to this task.

  - Add SSR for the ones that need it - **In progress** 🚧\

    _This is led by @ockham and @dmsnell._

    There's already initial support for the SSR of basic directive attributes and good progress on `wp-context`. The next challenge to solve is to figure out the APIs to access the inner HTML with the HTML (Tag) Processor.

  - Decide final names - **In progress** 🚧

    We are keeping a list of the decisions that need to be made here in the Tracking Issue.

- **Components**

  There hasn't been any progress on this, mostly due to the lack of need for components (directive tags). [@luisherranz opened an issue proposing their removal](https://github.com/WordPress/block-hydration-experiments/issues/152), as we couldn't find a single case where they add meaningful value and we might want to use them for other purposes in the future.

- **State Management**

  - Finish the Deep Signals implementation - [Finished](https://github.com/luisherranz/deepsignal) ✅
  - Decide on the recommended shape - **In progress** 🚧\
    _Same answer as in the "Directives - Decide final names"._
  - TypeScript support - **Not started** ⏸
  - Figure out if we want to expose some parts of the router and/or other configuration in the state ([example](https://github.com/c4rl0sbr4v0/wp-movies-demo/pull/15)) - **Not started** ⏸

- **Server-side rendering**
  - API to do SSRing - **In progress** 🚧\
    _Same answer as in the "Directives - Add SSR for the ones that need it"._
  - Serialize initial state - [Finished](https://github.com/WordPress/block-hydration-experiments/pull/147) ✅ 
  - Sort directives by priority - **Not started** ⏸

- **Client runtime**
  - Limit hydration when CSN is not possible [Finished](https://github.com/WordPress/block-hydration-experiments/pull/124) ✅
  - Deserialize state [Finished](https://github.com/WordPress/block-hydration-experiments/pull/147) ✅ ([mostly](https://github.com/WordPress/block-hydration-experiments/pull/147#issuecomment-1433454029))
  - Sort directives by priority - **In progress** 🚧

- **Bundling**
  - API to register directives/components - **Not started** ⏸
  - Enqueue directives/components present in the HTML - **Not started** ⏸
  - Ensure script execution order, deferring and prefetch - **Not started** ⏸
  - Choose final package name and shape - **In progress** 🚧\
    _Same answer as in the "Directives - Decide final names"._
  - Choose and implement dependency management - **In progress** 🚧\
    Barely started, just preliminary conversations between @luisherranz, @gziolo, @dmsnell and @youknowriad.

- **Client-side navigation**
  - Manual ([Finished](https://github.com/WordPress/block-hydration-experiments/pull/86) ✅) and automatic opt-in (**Not started** ⏸)
  - Router
    - Fetch directives/components scripts - **Not started** ⏸
    - Global state (`state.router.url`) - **Not started** ⏸
  - API to trigger virtual pageviews - **Not started** ⏸
  - Prefetching strategy - **Not started** ⏸

# Done

- https://github.com/WordPress/block-hydration-experiments/pull/81
- https://github.com/WordPress/block-hydration-experiments/pull/82
- https://github.com/WordPress/block-hydration-experiments/pull/83
- https://github.com/WordPress/block-hydration-experiments/pull/84
- https://github.com/WordPress/block-hydration-experiments/pull/85
- https://github.com/WordPress/block-hydration-experiments/pull/86
- https://github.com/WordPress/block-hydration-experiments/pull/88
- https://github.com/WordPress/block-hydration-experiments/pull/87
- https://github.com/WordPress/block-hydration-experiments/pull/90
- https://github.com/WordPress/block-hydration-experiments/pull/89
- https://github.com/WordPress/block-hydration-experiments/pull/91 (closed because it was finished)
- https://github.com/WordPress/block-hydration-experiments/pull/115
- https://github.com/WordPress/block-hydration-experiments/pull/119
- https://github.com/WordPress/block-hydration-experiments/pull/121
- https://github.com/WordPress/block-hydration-experiments/pull/122
- https://github.com/WordPress/block-hydration-experiments/pull/124
- https://github.com/WordPress/block-hydration-experiments/pull/127
- https://github.com/WordPress/block-hydration-experiments/pull/128
- https://github.com/WordPress/block-hydration-experiments/pull/139
- https://github.com/WordPress/block-hydration-experiments/pull/142
- https://github.com/WordPress/block-hydration-experiments/pull/147
- https://github.com/WordPress/block-hydration-experiments/pull/149
- https://github.com/WordPress/block-hydration-experiments/pull/156
- https://github.com/WordPress/block-hydration-experiments/pull/163
- https://github.com/WordPress/block-interactivity-experiments/pull/213
- https://github.com/WordPress/block-hydration-experiments/pull/103
- https://github.com/WordPress/block-hydration-experiments/pull/164
- https://github.com/WordPress/block-interactivity-experiments/pull/214
- https://github.com/WordPress/block-interactivity-experiments/pull/226

# In progress

- https://github.com/WordPress/block-hydration-experiments/issues/120

# Next

- https://github.com/WordPress/block-hydration-experiments/issues/154
- https://github.com/WordPress/block-hydration-experiments/issues/155
- https://github.com/WordPress/block-hydration-experiments/issues/126
- https://github.com/WordPress/block-hydration-experiments/issues/75
- https://github.com/WordPress/block-interactivity-experiments/issues/192
- https://github.com/WordPress/block-hydration-experiments/issues/152

# Decisions that need to be made

- [x] Find a better name for `wpx()` _(needed for the announcement blog post)_
  - https://github.com/WordPress/block-hydration-experiments/issues/136
- [x] https://github.com/WordPress/block-interactivity-experiments/issues/152 _(needed for the announcement blog post)_
- [x] Decide on whether to follow the HTML spec or not _(needed for the announcement blog post)_
  - https://github.com/WordPress/block-hydration-experiments/issues/132
- [ ] Decide the name of the client-side navigation meta tag.
- [ ] Find a way to use Preact's JSX pragma in the `view.js` files with backward compatibility.
- [ ] Decide whether `"interactive: true"` should be optional or not in the `block.json`.
- [x] #138 _(needed for the announcement blog post)_
- [x] #146
- [x] ~~Figure out how the store will work in static blocks~~: it won't.
- [ ] Figure out how we can pass objects to wp-context instead of a stringified JSON (in PHP and JS).
- [x] Decide if `wp-bind:value` should be bidirectional in inputs.
- [ ] Find names for the full/partial/isolated hydration types.
- [x] Decide if we should use `client-side transitions` or `client-side navigation`: we'll use `client-side navigation` from now on
- [x] ~~Figure out how to use context inside the derived state~~: we'll use selectors
- [x] Decide on whether to use `components` or not: we won't
- [x] Decide on the name of this repo. Something like `interactivity-api-proposal`. _(needed for the announcement blog post)_
- [ ] Is registering the `block.json` in the server a requirement?
- [ ] Is a single top-level node a requirement?
- [x] #159
- [ ] Decide how to name the DOM element that is passed down to the references (right now it's called `ref`)
- [x] https://github.com/WordPress/block-hydration-experiments/issues/160 _(needed for the announcement blog post)_
- [ ] Decide what pattern we should use for "multiple render path" directives like `wp-error-boundary` or `wp-suspense`
- [ ] Decide if we need to name `wp-html` with a word the warns about its risks, like `wp-dangerous-html`
 
# Experiments

- https://github.com/WordPress/gutenberg/pull/44034
- https://github.com/woocommerce/woocommerce-blocks/pull/7187
- https://github.com/WordPress/gutenberg/pull/44509
- https://github.com/woocommerce/woocommerce-blocks/issues/8219
- https://github.com/WordPress/gutenberg/pull/49305
- https://github.com/WordPress/gutenberg/pull/49621

**Comment by luisherranz** [comment]
I've opened [the `main-wp-directives-plugin` branch](https://github.com/WordPress/block-hydration-experiments/tree/main-wp-directives-plugin) with a basic skeleton of a plugin, including a basic `webpack` configuration and enqueuing of the runtime/vendor scripts.

**Comment by luisherranz** [comment]
I've added some basic tasks to the OP to get the client-side navigations working, which is our first task. 

These two experiments contain much of the required code:

- https://github.com/WordPress/gutenberg/pull/44034
- https://github.com/woocommerce/woocommerce-blocks/pull/7187

_We should rename `wp-client-transition` to `wp-link`._

**Comment by SantosGuillamot** [comment]
I have created a [Pull Request](https://github.com/WordPress/block-hydration-experiments/pull/81) to "Add the wp-link to all the relative links on the page". It is still a draft, but I opened it to keep the discussion about that specific task there.

- https://github.com/WordPress/block-hydration-experiments/pull/81

**Comment by luisherranz** [comment]
I've created a pull request to add the basic vdom + directives functionality.

- https://github.com/WordPress/block-hydration-experiments/pull/82

I'll now create another one for the router + `wp-link`.

**Comment by luisherranz** [comment]
I've created the pull request to add the router and the `wp-link` directive.

- https://github.com/WordPress/block-hydration-experiments/pull/83

**Comment by luisherranz** [comment]
I've created another pull request to change the `toVdom` logic to test removing the comment nodes and preserving the script's children:

- https://github.com/WordPress/block-hydration-experiments/pull/84

**Comment by DAreRodz** [comment]
I'll be working on adding page transitions to the client-side navigations using the Shared Element Transition API. I'll share here a link to the PR soon.

**Comment by luisherranz** [comment]
I've created a PR to add support for CSS loading during client-side navigations:

- https://github.com/WordPress/block-hydration-experiments/pull/85

**Comment by luisherranz** [comment]
I've opened a PR to add a basic opt-in mechanism based on a custom meta tag:

- https://github.com/WordPress/block-hydration-experiments/pull/86

**Comment by SantosGuillamot** [comment]
I've opened a PR to add `prefetch` to all links and prevent scrolling in the pagination:
* https://github.com/WordPress/block-hydration-experiments/pull/87

While doing that, we realized that the HTML of the parent blocks contains the children, so we were parsing the HTML multiple times. For that, we change the filters to only trigger for the Query Loop and the Template Parts until we figure out a better solution.

**Comment by luisherranz** [comment]
Another PR to add an admin page with a checkbox to toggle client-side navigations (for testing purposes only):

- https://github.com/WordPress/block-hydration-experiments/pull/88

**Comment by luisherranz** [comment]
I did a couple of bug fixes that we noticed while working on this [demo](https://wpmoviesdemo.wpcomstaging.com/):

- https://github.com/WordPress/block-hydration-experiments/pull/90
- https://github.com/WordPress/block-hydration-experiments/pull/89

**Comment by luisherranz** [comment]
I've opened an issue to talk about limiting the hydration surface when the site doesn't support client-side navigations:

- https://github.com/WordPress/block-hydration-experiments/issues/93

**Comment by luisherranz** [comment]
@yscik opened an issue to talk about how to avoid using strings to define the directives in JSX.

- https://github.com/WordPress/block-hydration-experiments/issues/94 

@santosguillamot and I did a PR to show how server-side rendering in PHP could look like using an HTML parser.

- https://github.com/WordPress/block-hydration-experiments/pull/100

**Comment by luisherranz** [comment]
I closed the build-time SSR in PHP proof of concept because @ockham and @dmsnell have started working on a new run-time version based on the `WP_HTML_Tag_Processor`, which is much more promising.

- https://github.com/WordPress/block-hydration-experiments/pull/100

**Comment by luisherranz** [comment]
I have created a PR to start using `createTreeWalker`. I'm not going to be able to dedicate time to it in the next few days, so if anyone wants to finish it, no problem 🙂

- https://github.com/WordPress/block-hydration-experiments/pull/103

**Comment by SantosGuillamot** [comment]
I have created a PR to handle the `CDATA` nodes based on @DAreRodz proposal.

* https://github.com/WordPress/block-hydration-experiments/pull/115

**Comment by luisherranz** [comment]
Latest work related to this:

- https://github.com/WordPress/block-hydration-experiments/pull/118
- https://github.com/WordPress/block-hydration-experiments/pull/119
- https://github.com/WordPress/block-hydration-experiments/pull/121
- https://github.com/WordPress/block-hydration-experiments/pull/122

**Comment by luisherranz** [comment]
I've started working on the limit hydration issue:

- Issue: https://github.com/WordPress/block-hydration-experiments/issues/93
- PR: https://github.com/WordPress/block-hydration-experiments/pull/124

**Comment by luisherranz** [comment]
The PR is ready for review:

- https://github.com/WordPress/block-hydration-experiments/pull/124

**Comment by luisherranz** [comment]
I forgot to mention here these two PRs, sorry!

- https://github.com/WordPress/block-hydration-experiments/pull/127
- https://github.com/WordPress/block-hydration-experiments/pull/128

I've also updated the opening post 🙂

**Comment by DAreRodz** [comment]
I did a minor fix in `navigate`, which was failing with relative paths. The issue was discovered in https://github.com/woocommerce/woocommerce-blocks/pull/8220#issuecomment-1397238113.

- https://github.com/WordPress/block-hydration-experiments/pull/135

**Comment by DAreRodz** [comment]
I'll be working on implementing `wp-context` to support nested context, merging them.

- https://github.com/WordPress/block-hydration-experiments/issues/137

**Comment by luisherranz** [comment]
I've added a list of decisions to the opening post that we need to take rather soon. Please feel free to add the ones you find. 

_If you can edit the opening post, just write a comment and I'll update it._

**Comment by luisherranz** [comment]
I've opened an issue to discuss the use of namespaces in the store:

- https://github.com/WordPress/block-hydration-experiments/issues/138

**Comment by DAreRodz** [comment]
This PR implements https://github.com/WordPress/block-hydration-experiments/issues/137 and makes `wp-context` extensible. It's ready to review.

- https://github.com/WordPress/block-hydration-experiments/pull/139

**Comment by DAreRodz** [comment]
In https://github.com/WordPress/block-hydration-experiments/pull/142, I've moved the `wp-` prefixes to a `constants.js` file to make it easier to update those values―just in case.

- https://github.com/WordPress/block-hydration-experiments/pull/142

---

**PS:** PR https://github.com/WordPress/block-hydration-experiments/pull/139 is already merged.

**Comment by luisherranz** [comment]
As part of the decisions that we need to make before the proposal, I've opened a PR to rename `client-side transitions` with `client-side navigation`:

- https://github.com/WordPress/block-hydration-experiments/pull/145

**Comment by DAreRodz** [comment]
I started working on serializing the store in PHP and have made good progress. The only missing part would be hydrating the serialized store on the client.

- https://github.com/WordPress/block-hydration-experiments/pull/147

**Comment by luisherranz** [comment]
I've opened an issue proposing to remove the directive tags (components) from the proposal because they are not adding any meaningful value today, and if we publish them as they are, we can't use them for other (hopefully more interesting) purposes in the future:

- https://github.com/WordPress/block-hydration-experiments/issues/152

I've also reopened the `store` naming discussion to decide if we need to use something less generic, like `wp_store`:

- https://github.com/WordPress/block-hydration-experiments/issues/136

**Comment by SantosGuillamot** [comment]
I've opened an issue to discuss how to fetch directives scripts after client-side navigation, which is needed for [the movies demo](https://github.com/c4rl0sbr4v0/wp-movies-demo/pull/19#issuecomment-1436547876).
* https://github.com/WordPress/block-hydration-experiments/issues/153

**Comment by DAreRodz** [comment]
I created two new issues for merging new state and context during client-side navigations.

- https://github.com/WordPress/block-hydration-experiments/issues/154
- https://github.com/WordPress/block-hydration-experiments/issues/155

**Comment by luisherranz** [comment]
I've added a **High-level overview** section to the opening post with information about the current status.

**Comment by SantosGuillamot** [comment]
I've started a pull request to [Add `wp-show` directive attribute](https://github.com/WordPress/block-hydration-experiments/pull/156). Right now, it only exists the `wp-show` directive tag (component).
* https://github.com/WordPress/block-hydration-experiments/pull/156

I've added it to the opening post (In Progress). Please let me know if it should be in any other place.

**Comment by bernhardreiter** [comment]
> * Add SSR for the ones that need it - In progress ￼\
>
> This is led by @bernhardreiter and @dmsnell.

You've probably wanted to mention somebody else with a similar name.

**Comment by luisherranz** [comment]
Oh my. Yes, that was @ockham, sorry!

**Comment by SantosGuillamot** [comment]
I've opened an issue to discuss What should be the HTML structure returned when `wp-show` is false?

* https://github.com/WordPress/block-hydration-experiments/issues/159

**Comment by michalczaplinski** [comment]
I've opened an issue to discuss if we want to expose parts of the router (or other API internals) in the store:

- https://github.com/WordPress/block-hydration-experiments/issues/160

**Comment by dmsnell** [comment]
I'll repeat it here because I think it will be important.

>  Decide on whether to use wp- or data-wp-

If we can avoid using the `wp-` prefix we'll have much better opportunity to avoid needless performance hits in content without directives. This isn't about `data-wp-` vs. `wp-` but rather something like `wp-` vs. `wpx-`.

It'd be extremely advantageous to be able to perform this quick check and bail all directive processing.

```php
function process_directives( $html ) {
	// Some posts will have `wpx-` without having directives,
	// But no posts will have directives without having `wpx-`.
	if ( false === strpos( $html, 'wpx-' ) ) {
		return $html;
	}
}
```

Looking for `wp-` conflates with all sorts of Gutenberg prefixes otherwise.

**Comment by luisherranz** [comment]
A small update:

- Michal opened a PR to add temporary support for fetching new scripts in client-side navigation:
  - https://github.com/WordPress/block-hydration-experiments/pull/164
- We decided on whether to use components or not: we won't
  - https://github.com/WordPress/block-hydration-experiments/issues/152
- David opened a PR to add support for client-side navigation to `wp-ignore`
  - https://github.com/WordPress/block-hydration-experiments/pull/163

**Comment by DAreRodz** [comment]
I've merged the PR that makes `wp-ignore` work on client-side navigations.

- https://github.com/WordPress/block-hydration-experiments/pull/163

Same with this other PR, which refactors the e2e tests a bit to prevent `fetch` failures during client-side navigations.

- https://github.com/WordPress/block-hydration-experiments/pull/167

**Comment by SantosGuillamot** [comment]
I have started a pull request to add the `wp-text` directive to stop using `wp-bind:children` in the current examples.
* https://github.com/WordPress/block-hydration-experiments/pull/173

**Comment by luisherranz** [comment]
I've opened a couple of issues, one to make the hydration more resilient (and make it work with `template`) and the other to see how we could integrate the new View Transitions API:

- https://github.com/WordPress/block-interactivity-experiments/issues/172
- https://github.com/WordPress/block-interactivity-experiments/issues/178

**Comment by luisherranz** [comment]
It's very preliminary yet, but @darerodz and I have started an experiment to do client-side form submissions on the Comments Form block:

- https://github.com/WordPress/gutenberg/pull/49305

**Comment by luisherranz** [comment]
Added this to the list, mentioned by @tomjn [here](https://github.com/WordPress/wp-movies-demo/issues/36):

- https://github.com/WordPress/block-interactivity-experiments/issues/192

**Comment by luisherranz** [comment]
Another issue related to the router:

- https://github.com/WordPress/block-interactivity-experiments/issues/194

**Comment by michalczaplinski** [comment]
I've reopened 
- woocommerce/woocommerce-blocks#136 

because it became clear that `wp_store` is not the right final name. It would be amazing if we could decide before publishing the blog post introducing the Interactivity API because having a bad name is easy for people to nitpick.

Realistically, we might need more time, though 🙂

**Comment by luisherranz** [comment]
We finished the basic functionality of the Comments Form submission experiment:

- https://github.com/WordPress/gutenberg/pull/49305#issuecomment-1487141538

**Comment by luisherranz** [comment]
@artemiomorales started this experiment of a lightbox for images, similar to the one in Medium:

- https://github.com/WordPress/gutenberg/pull/49621

**Comment by luisherranz** [comment]
I've added support for the `!` operator: `"!state.boolean"`

- https://github.com/WordPress/block-interactivity-experiments/pull/213
- https://github.com/WordPress/block-interactivity-experiments/pull/214

I've also improved the logic of `data-wp-bind` and added some e2e tests.

**Comment by luisherranz** [comment]
I finally merged the `createTreeWalker` version:

- https://github.com/WordPress/block-interactivity-experiments/pull/103

@darerodz and I have also started working on a branch to simplify the runtime so we can start testing it with core blocks:

- https://github.com/WordPress/gutenberg/issues/49868

**Comment by DAreRodz** [comment]
I haven't opened a PR yet, but I just started working on sorting directives by priority. I'll update this comment with the PR link soon.

**Comment by luisherranz** [comment]
We also merged this fix:
- https://github.com/WordPress/block-interactivity-experiments/pull/226

**Comment by luisherranz** [comment]
I'm going to close this issue as part of the migration to the Gutenberg repository.

[This is the current Tracking Issue](https://github.com/WordPress/gutenberg/issues/51056) on Gutenberg. Please refer to it from now on.
